### PR TITLE
prevent exit command from accepting arguments

### LINKED ISSUE #197: [PE-D] Exit 0 also exit the app
No error message displayed. Exit 0 passes as an exit command

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: vuhieunguyen/ped#22

### PR DESCRIPTION
**Pull request by kevinswk94**
fixing a very serious bug kindly pointed out by a bug hunter extraordinaire

### CODE REVIEW

**Review by AdarshChugani — APPROVED** [review]
Thanks for fixing the bug, Kevin.
I noticed that the reviewer marked the bug as having a priority of very high.

I really appreciate the fix!
👍

**Comment by kevinswk94** [comment]
> Thanks for fixing the bug, Kevin.
> I noticed that the reviewer marked the bug as having a priority of very high.
> 
> I really appreciate the fix!
> 👍

Thanks Adarsh! It's crucial that serious bugs like this be fixed immediately.

**Comment by AdarshChugani** [comment]
> > Thanks for fixing the bug, Kevin.
> > I noticed that the reviewer marked the bug as having a priority of very high.
> > I really appreciate the fix!
> > 👍
> 
> Thanks Adarsh! It's crucial that serious bugs like this be fixed immediately.

I can't believe we let this slip past our QA!

**Comment by sharadhr** [comment]
Well done, Kevin! I don't know what we would've done without the bug reporter's keen eye and sense of community!

**Comment by muhd97** [comment]
👏

**Pull request merged**
