### PR TITLE
update ModifyCommand to be able to modify Recipe's calorie amount

### PR DESCRIPTION
**Pull request by muhd97**
allow a user to modify the calorie of a recipe using the modify command

### CODE REVIEW

**Review by AdarshChugani — APPROVED** [review]
Looks good 👍

**Review by sharadhr — APPROVED** [review]
LGTM!

**Comment by muhd97** [comment]
allow finding a recipe with keywords in its name

**Review by sharadhr — DISMISSED** [review]
Reset this commit, and we’ll merge this PR. Let’s have one PR per feature

**Comment by muhd97** [comment]
> Reset this commit, and we’ll merge this PR. Let’s have one PR per feature

done!

**Review by kevinswk94 — APPROVED** [review]
LGTM!

**Pull request merged**
