### PR TITLE
New user interface: split view and light mode

### LINKED ISSUE #180: Revamp GUI
Revamp the GUI

### PR DESCRIPTION
**Pull request by sharadhr**

### CODE REVIEW

**Review by AdarshChugani — APPROVED** [review]
Thanks Sharadh! 👍 👍 
Looks good

I can add in the difficulty/favourite/serving size features if needed

**Review by kevinswk94 — APPROVED** [review]
Great job Sharadh!

**Review by AdarshChugani — APPROVED** [review]
Thanks Sharadh! 👍 👍
Looks good

I'll add in some of the other GUI elements

**Review by muhd97 — APPROVED** [review]
Good job Sharadh!!

**Pull request merged**
